site_name: PMLB
site_url: http://epistasislab.github.io/penn-ml-benchmarks
site_author: Trang Le, Weixuan Fu
site_description: Documentation for PMLB, a large curated repository of benchmark datasets for evaluating supervised machine learning algorithms.

repo_url: https://github.com/EpistasisLab/penn-ml-benchmarks
edit_uri: edit/gh_pages/docs_sources/
docs_dir: docs_sources/
site_dir: docs/
theme: readthedocs

markdown_extensions:
  - tables
  - fenced_code

copyright: Developed by Randal S. Olson, William La Cava, Trang Le, Weixuan Fu and others at the University of Pennsylvania

nav:
- Home: index.md
- Installation: installing.md
- Using PMLB python wrapper: using.md
- Contributing: contributing.md
- How to verify source: how-to-verify-source.md
- Browse datasets: browse-datasets.md
