# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - master
      - PMLB2.0
  pull_request:
    branches:
      - master
      - PMLB2.0
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install nose numpy scipy tabulate pandas pyyaml requests parameterized matplotlib seaborn mkdocs pandas-profiling
    - name: Test with nose
      run: |
        nosetests -s -v

    - name: Generate profiling reports
      run: |
        python -m pmlb.profiling

    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1
    - name: Install R packages
      run: Rscript -e 'install.packages(c("rmarkdown", "ggplot2", "httr", "plotly", "dplyr", "htmlwidgets", "htmltools", "jsonlite", "readr", "DT"))'
    - name: Build site
      run: Rscript -e 'rmarkdown::render_site(input = "docs_sources")'
    # - name: Build
    #   run: mkdocs build

    - run: ls -lhR docs/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        # keep existing files if no changes, unless commit message has regenerate_profiles
        keep_files: ${{ env.regenerate_profiles == null }}

